databases:
  - name: butik-emilly-db
    databaseName: butik_emilly_db
    user: butik_emilly
    plan: free

services:
  - type: web
    name: butik-emilly
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: butik-emilly-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.6"

